# Generated by Django 4.0 on 2021-12-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gol_pendapatan',
            field=models.IntegerField(null=True),
        ),
    ]
