# Generated by Django 4.0 on 2021-12-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_userprofile_gol_pendapatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kota',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='provinsi',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Telepon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telepon', models.CharField(max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
