# Generated by Django 4.0 on 2021-12-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_kota_alter_userprofile_provinsi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Telepon',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
