# Generated by Django 4.0 on 2021-12-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=25, null=True)),
                ('max_member', models.IntegerField(null=True)),
                ('min_member', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('deadline', models.IntegerField(null=True)),
                ('host_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
