# Generated by Django 4.0 on 2021-12-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0003_rename_rooms_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
