# Generated by Django 4.0 on 2021-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0004_alter_room_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
