# Generated by Django 4.0 on 2021-12-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0005_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
