# Generated by Django 4.0 on 2021-12-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0009_remove_member_room_member_room_remove_member_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role_room',
            field=models.CharField(default='Member', max_length=16),
        ),
    ]
