# Generated by Django 4.0 on 2021-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0010_member_role_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role_room',
            field=models.CharField(choices=[('Host', 'Host'), ('Member', 'Member')], default='Member', max_length=16),
        ),
    ]
