# Generated by Django 4.0 on 2021-12-30 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arisan', '0011_alter_member_role_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(null=True)),
                ('room', models.ManyToManyField(to='arisan.Room')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
