# Generated by Django 4.0 on 2021-12-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0012_past_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='deadline',
            new_name='intervaldate',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_finish',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_started',
        ),
        migrations.AddField(
            model_name='room',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Bill', 'Bill')], default='Bill', max_length=4)),
                ('room_id', models.ManyToManyField(to='arisan.Room')),
            ],
        ),
    ]
