# Generated by Django 4.0 on 2021-12-30 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arisan', '0016_remove_member_user_member_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ManyToManyField(related_name='user_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='past_winner',
            name='user',
        ),
        migrations.AddField(
            model_name='past_winner',
            name='user',
            field=models.ManyToManyField(related_name='user_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
