# Generated by Django 4.0 on 2021-12-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0017_remove_member_user_member_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='past_winner',
            name='room',
        ),
        migrations.RemoveField(
            model_name='past_winner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host_id',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Past_Winner',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
