# Generated by Django 4.0 on 2021-12-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('arisan', '0019_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='past_winner',
            unique_together={('user', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='roomroles',
            unique_together={('user', 'room')},
        ),
    ]
