# Generated by Django 4.0.1 on 2022-01-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0020_alter_past_winner_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
