# Generated by Django 4.0.1 on 2022-01-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0021_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
