# Generated by Django 4.0.1 on 2022-01-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0022_alter_payment_finished_at_alter_payment_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
