# Generated by Django 4.0.1 on 2022-01-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arisan', '0024_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
